import "oaidl.idl";
import "ocidl.idl";

[
	object,
	dual,
	uuid(BB4AB49B-5DBE-4B2D-B3EC-1CE8D9EA243C)
]
interface IFoo : IDispatch {
	[id(1), local] HRESULT Start();
	[id(2), local] HRESULT Stop();
	[id(3), local] HRESULT DoSomething();
}
[
	uuid(020E5D66-B659-4B59-A5FA-B3CFA022E807),
	version(1.0),
	helpstring("Type library for audio server")
]
library FooLib {
	importlib("stdole2.tlb");
	[
		uuid(A7972B86-E3FD-44F0-9C09-E279C102FB11)
	]
	coclass Foo
	{
		[default] interface IFoo;
	}
}
